export { Lab1 } from "./Lab1";
export { Lab2 } from "./Lab2";
export { Lab3 } from "./Lab3";
export { Lab4 } from "./Lab4";
export { Lab5 } from "./Lab5";
export { Lab6 } from "./Lab6";
export { Lab7 } from "./Lab7";
export { Lab8 } from "./Lab8";
export { Lab9 } from "./Lab9";
